### PR TITLE
Video System Remake, Footer More Clear

### PR DESCRIPTION
**Pull request by DrPanayioths**

### CODE REVIEW

**Comment by DrPanayioths** [comment]
@NoobJsPerson Can You Also Check This Pull Request also

**Comment by NoobJsPerson** [comment]
image
this doesn't look right

**Comment by DrPanayioths** [comment]
i will check it and repair and tell you when is working right

**Comment by DrPanayioths** [comment]
@NoobJsPerson Can You Check It Again

**Comment by NoobJsPerson** [comment]
To be completely honest, I don't think it makes it look that much better. I kind of like the current layout more

**Pull request closed without merging**
